/**
 * Internal trade links for the “Built for Service Professionals” section (all industry routes).
 */
export const SERVICE_PROFESSIONAL_TRADE_LINKS = [
  { id: "hvac", slug: "hvac-review-software", labelKey: "tradeHvac" as const },
  { id: "plumbing", slug: "plumber-review-software", labelKey: "tradePlumbing" as const },
  { id: "electrical", slug: "electrical-review-software", labelKey: "tradeElectrical" as const },
  { id: "roofing", slug: "roofing-review-software", labelKey: "tradeRoofing" as const },
  { id: "landscaping", slug: "landscaping-review-software", labelKey: "tradeLandscaping" as const },
  { id: "cleaning", slug: "cleaning-service-review-software", labelKey: "tradeCleaning" as const },
  { id: "garage-door", slug: "garage-door-review-software", labelKey: "tradeGarageDoor" as const },
  { id: "pest-control", slug: "pest-control-review-software", labelKey: "tradePestControl" as const },
  { id: "tree-service", slug: "tree-service-review-software", labelKey: "tradeTreeService" as const },
  { id: "pool-service", slug: "pool-service-review-software", labelKey: "tradePoolService" as const },
  { id: "pressure-washing", slug: "pressure-washing-review-software", labelKey: "tradePressureWashing" as const },
  { id: "general-contractor", slug: "general-contractor-review-software", labelKey: "tradeGeneralContractor" as const },
  { id: "painting-contractor", slug: "painting-contractor-review-software", labelKey: "tradePaintingContractor" as const },
  { id: "flooring-contractor", slug: "flooring-contractor-review-software", labelKey: "tradeFlooringContractor" as const },
  { id: "fence-contractor", slug: "fence-contractor-review-software", labelKey: "tradeFenceContractor" as const },
  { id: "deck-builder", slug: "deck-builder-review-software", labelKey: "tradeDeckBuilder" as const },
  { id: "window-cleaning", slug: "window-cleaning-review-software", labelKey: "tradeWindowCleaning" as const },
  { id: "carpet-cleaning", slug: "carpet-cleaning-review-software", labelKey: "tradeCarpetCleaning" as const },
  { id: "restoration", slug: "restoration-review-software", labelKey: "tradeRestoration" as const },
  { id: "appliance-repair", slug: "appliance-repair-review-software", labelKey: "tradeApplianceRepair" as const },
  { id: "chimney-service", slug: "chimney-service-review-software", labelKey: "tradeChimneyService" as const },
  { id: "masonry-contractor", slug: "masonry-contractor-review-software", labelKey: "tradeMasonryContractor" as const },
  { id: "concrete-contractor", slug: "concrete-contractor-review-software", labelKey: "tradeConcreteContractor" as const },
  { id: "moving-company", slug: "moving-company-review-software", labelKey: "tradeMovingCompany" as const },
  { id: "insulation-contractor", slug: "insulation-contractor-review-software", labelKey: "tradeInsulationContractor" as const },
  { id: "solar-installer", slug: "solar-installer-review-software", labelKey: "tradeSolarInstaller" as const },
] as const;
